apiVersion: v1
kind: Pod
metadata:
  name: kubectl-proxy
spec:
  containers:
  - name: kubectl-proxy
    image: demoreg.azurecr.io/kazusato/kubectl-proxy:1.10-0.1.0

  imagePullSecrets:
  - name: demoreg-reader3-secret
