apiVersion: v1
kind: Pod
metadata:
  name: soba-order-controller
spec:
  containers:
  - name: kubectl-proxy
    image: demoreg.azurecr.io/kazusato/kubectl-proxy:1.10-0.1.0
  - name: soba-order-controller
    image: demoreg.azurecr.io/kazusato/soba-order-controller:0.1.7
  imagePullSecrets:
  - name: demoreg-reader3-secret

